services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: kestra
      POSTGRES_DB: kestra
    ports:
      - "5432:5432"
    volumes:
      - postgres_data3:/var/lib/postgresql/data
    networks:
      - kestra_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - kestra_network


  kestra:
    image: kestra/kestra:latest
    container_name: kestra
    environment:
      KESTRA_CONFIGURATION_STORAGE_TYPE: postgres
      KESTRA_CONFIGURATION_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kestra
      KESTRA_CONFIGURATION_DATASOURCE_USERNAME: kestra
      KESTRA_CONFIGURATION_DATASOURCE_PASSWORD: kestra
    ports:
      - "8080:8080"
    user: root  # Run as root user
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
      - /tmp:/tmp  # Mount temporary directory
      - kestra_data:/app/data
    command: ["server", "local"]  # Start Kestra server in local mode
    depends_on:
      - postgres
    networks:
      - kestra_network

volumes:
  postgres_data3:
  kestra_data:
  pgadmin_data:

networks:
  kestra_network:
    driver: bridge